#spring.application.name=Gong-Soccer

spring:
  application:
    name: Gong-Soccer
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${SPRING_DATA_SOURCE}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: 3600000

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true